const $=s=>document.querySelector(s), panels=[...document.querySelectorAll('.panel')], steps=[...document.querySelectorAll('.step')];let current=0,file=null,timer=null;
function show(i){current=Math.max(0,Math.min(i,panels.length-1));panels.forEach((p,n)=>p.classList.toggle('active',n===current));steps.forEach((s,n)=>s.classList.toggle('active',n===current));window.scrollTo({top:Math.max(0,document.querySelector('.workspace').offsetTop-24),behavior:'smooth'});}
function valid(){if(current===0&&!file){$('#dropzone').classList.add('drag');setTimeout(()=>$('#dropzone').classList.remove('drag'),600);return false}if(current===1&&!$('#accept').checked){$('.check-row').scrollIntoView({behavior:'smooth'});return false}return true}
steps.forEach((s,i)=>s.onclick=()=>{if(i<=current||valid())show(i)});document.querySelectorAll('.next').forEach(b=>b.onclick=()=>{if(valid())show(current+1)});document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show(current-1));
function choose(f){if(!f||!f.name.toLowerCase().endsWith('.zip')){alert('Selecciona un ZIP CNH.');return}file=f;$('#file-name').textContent=f.name;$('#file-size').textContent=(f.size/1048576).toFixed(1)+' MB';$('#file-card').classList.remove('hidden');$('#dropzone').classList.add('hidden');$('#summary-file').textContent=f.name}
$('#source-file').onchange=e=>choose(e.target.files[0]);['dragenter','dragover'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.add('drag')}));$('#dropzone').ondrop=e=>{e.preventDefault();$('#dropzone').classList.remove('drag');choose(e.dataTransfer.files[0])};$('#remove-file').onclick=()=>{file=null;$('#source-file').value='';$('#file-card').classList.add('hidden');$('#dropzone').classList.remove('hidden')};
$('#crs').onchange=e=>$('#summary-crs').textContent=e.target.value;$('#output-mode').onchange=e=>$('#summary-mode').textContent=e.target.value==='clean'?'Solo puntos válidos':'Todos con marcas QC';
function add(form,id,name=id){const el=$('#'+id);form.append(name,el.type==='checkbox'?String(el.checked):el.value)}
function progress(v,s){$('#progress').classList.remove('hidden');$('#bar').style.width=v+'%';$('#percent').textContent=v+'%';$('#stage').textContent=s}
async function poll(id){try{const r=await fetch('/api/jobs/'+id),d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo consultar el trabajo.');progress(d.progress,d.stage);if(d.status==='completed'){timer=null;$('#progress').classList.add('hidden');$('#result').classList.remove('hidden');const s=d.report.summary;$('#input-count').textContent=s.input_points.toLocaleString('es-ES');$('#kept-count').textContent=s.kept_points.toLocaleString('es-ES');$('#kept-pct').textContent=s.kept_pct+'%';$('#download').href=d.download_url}else if(d.status==='failed')throw Error(d.error||'La limpieza ha fallado.');else timer=setTimeout(()=>poll(id),2500)}catch(e){timer=null;$('#error-text').textContent=e.message;$('#error').classList.remove('hidden');$('#export').disabled=false}}
$('#export').onclick=async()=>{if(!file||!$('#accept').checked){show(file?1:0);return}$('#export').disabled=true;$('#result').classList.add('hidden');$('#error').classList.add('hidden');progress(1,'Cargando archivo local');const f=new FormData();f.append('file',file);f.append('accept_hypotheses','true');['crs','output-mode','yield-range','min-yield','max-yield','speed-range','min-speed','max-speed','smooth-speed','speed-change','minimum-width','min-width','moisture-range','min-moisture','max-moisture','standard-deviation','stddev'].forEach(id=>add(f,id,id.replaceAll('-','_')));try{const r=await fetch('/api/jobs',{method:'POST',body:f}),d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo iniciar.');poll(d.id)}catch(e){$('#error-text').textContent=e.message;$('#error').classList.remove('hidden');$('#progress').classList.add('hidden');$('#export').disabled=false}};
