/* Monitor-aware defaults layered over the filtered interface. */
let presetUploadToken=null,presetProfiles=[],selectedPresetId='auto_monitor';
const presetQuery=s=>document.querySelector(s);
const presetStyle=document.createElement('style');presetStyle.textContent=`
.preset-box{border:1px solid var(--leaf);background:#f3f7e8;padding:18px;margin-bottom:16px}.preset-box>label{display:block;font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;margin-bottom:8px}.detect-grid{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;margin-top:12px;padding-top:12px;border-top:1px solid #ced9bf}.detect-grid b,.detect-grid small{display:block}.detect-grid small{color:var(--muted);font-size:10px;margin-top:4px}.confidence{font-size:9px;font-weight:900;text-transform:uppercase;background:var(--lime);padding:5px 7px}.preset-description{font-size:10px;color:var(--muted);margin:8px 0 0}.detect-wait{font-size:11px;color:var(--muted)}
`;document.head.appendChild(presetStyle);
const filterPanel=presetQueryAll('.panel')[2];
function presetQueryAll(s){return [...document.querySelectorAll(s)]}
const presetBox=document.createElement('div');presetBox.className='preset-box';presetBox.innerHTML=`<label for="monitor-preset">Perfil automático por monitor</label><select id="monitor-preset" disabled><option>Selecciona primero el ZIP</option></select><p class="preset-description" id="preset-description">Se leerán únicamente metadatos y anchos candidatos.</p><div class="detect-grid"><div><b id="detected-monitor">Monitor pendiente de analizar</b><small id="detected-evidence">No se asignará un modelo sin evidencia.</small></div><span class="confidence" id="detected-confidence">pendiente</span></div>`;
filterPanel.querySelector('.notice').before(presetBox);
function applyPreset(profile){const s=profile.settings,map={yield_range:'yield-range',min_yield_t_ha:'min-yield',max_yield_t_ha:'max-yield',speed_range:'speed-range',min_speed_m_s:'min-speed',max_speed_m_s:'max-speed',smooth_speed:'smooth-speed',minimum_width:'minimum-width',min_width_m:'min-width',standard_deviation:'standard-deviation',max_yield_stddev:'stddev',moisture_range:'moisture-range',min_moisture_pct:'min-moisture',max_moisture_pct:'max-moisture'};Object.entries(map).forEach(([key,id])=>{const el=presetQuery('#'+id);if(el.type==='checkbox')el.checked=Boolean(s[key]);else el.value=s[key]});presetQuery('#speed-change').value=Math.round(s.max_speed_change_ratio*100);presetQuery('#preset-description').textContent=profile.description;selectedPresetId=profile.id}
async function analyzeMonitor(fileToAnalyze){presetUploadToken=null;presetQuery('#monitor-preset').disabled=true;presetQuery('#detected-monitor').textContent='Analizando familia de monitor…';presetQuery('#detected-evidence').textContent='Leyendo software CN1 y ancho dominante.';presetQuery('#detected-confidence').textContent='analizando';const form=new FormData();form.append('file',fileToAnalyze);try{const response=await fetch('/api/presets',{method:'POST',body:form}),data=await response.json();if(!response.ok)throw Error(data.error||'No se pudo detectar el monitor.');presetUploadToken=data.upload_token;presetProfiles=data.presets;const select=presetQuery('#monitor-preset');select.innerHTML='';presetProfiles.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.title;select.appendChild(o)});select.value=data.recommended_preset;select.disabled=false;const d=data.detection;presetQuery('#detected-monitor').textContent=d.probable_monitor;presetQuery('#detected-evidence').textContent=`${d.machine_software||d.family} · monitor de rendimiento ${d.yield_software||'sin versión'} · ancho dominante ${d.dominant_width_m??'—'} m`;presetQuery('#detected-confidence').textContent=d.confidence==='medium'?'probable':d.confidence;applyPreset(presetProfiles.find(p=>p.id===data.recommended_preset))}catch(error){presetQuery('#detected-monitor').textContent='No se pudo identificar';presetQuery('#detected-evidence').textContent=error.message;presetQuery('#detected-confidence').textContent='sin perfil'}}
presetQuery('#monitor-preset').addEventListener('change',event=>{const p=presetProfiles.find(x=>x.id===event.target.value);if(p)applyPreset(p)});
presetQuery('#source-file').addEventListener('change',event=>{if(event.target.files[0])analyzeMonitor(event.target.files[0])});
presetQuery('#dropzone').addEventListener('drop',event=>{if(event.dataTransfer.files[0])analyzeMonitor(event.dataTransfer.files[0])});
presetQuery('#remove-file').addEventListener('click',()=>{presetUploadToken=null;presetProfiles=[];presetQuery('#monitor-preset').innerHTML='<option>Selecciona primero el ZIP</option>';presetQuery('#monitor-preset').disabled=true;presetQuery('#detected-monitor').textContent='Monitor pendiente de analizar'});
function presetAdd(form,id,name=id){const el=presetQuery('#'+id);form.append(name,el.type==='checkbox'?String(el.checked):el.value)}
function presetProgress(value,stage){presetQuery('#progress').classList.remove('hidden');presetQuery('#bar').style.width=value+'%';presetQuery('#percent').textContent=value+'%';presetQuery('#stage').textContent=stage}
async function presetPoll(id){try{const response=await fetch('/api/jobs/'+id),data=await response.json();if(!response.ok)throw Error(data.error||'No se pudo consultar el trabajo.');presetProgress(data.progress,data.stage);if(data.status==='completed'){presetQuery('#progress').classList.add('hidden');presetQuery('#result').classList.remove('hidden');const s=data.report.summary;presetQuery('#input-count').textContent=s.input_points.toLocaleString('es-ES');presetQuery('#kept-count').textContent=s.kept_points.toLocaleString('es-ES');presetQuery('#kept-pct').textContent=s.kept_pct+'%';presetQuery('#download').href=data.download_url}else if(data.status==='failed')throw Error(data.error||'La limpieza ha fallado.');else setTimeout(()=>presetPoll(id),2500)}catch(error){presetQuery('#error-text').textContent=error.message;presetQuery('#error').classList.remove('hidden');presetQuery('#export').disabled=false}}
presetQuery('#export').addEventListener('click',async event=>{event.preventDefault();event.stopImmediatePropagation();if(!presetUploadToken){presetQuery('#error-text').textContent='Espera a que termine la detección del monitor o selecciona de nuevo el ZIP.';presetQuery('#error').classList.remove('hidden');return}presetQuery('#export').disabled=true;presetQuery('#result').classList.add('hidden');presetQuery('#error').classList.add('hidden');presetProgress(1,'Preparando perfil de monitor');const form=new FormData();form.append('upload_token',presetUploadToken);form.append('preset_id',selectedPresetId);['crs','output-mode','yield-range','min-yield','max-yield','speed-range','min-speed','max-speed','smooth-speed','speed-change','minimum-width','min-width','moisture-range','min-moisture','max-moisture','standard-deviation','stddev'].forEach(id=>presetAdd(form,id,id.replaceAll('-','_')));try{const response=await fetch('/api/jobs',{method:'POST',body:form}),data=await response.json();if(!response.ok)throw Error(data.error||'No se pudo iniciar.');presetPoll(data.id)}catch(error){presetQuery('#error-text').textContent=error.message;presetQuery('#error').classList.remove('hidden');presetQuery('#progress').classList.add('hidden');presetQuery('#export').disabled=false}},true);
