select nombre,
indice_cosecha ic,
ms_cosecha ms_cos , 
ms_residuo  ms_res, 
humedad , 
precio, 
extraccioncosechan n_cos,
extraccioncosechap p_cos,
extraccioncosechak k_cos,
contenidocosechac c_cos,
extraccioncosechas s_cos,
extraccioncosechaca ca_cos,
extraccioncosechamg mg_cos,
extraccioncosechab b_cos,
extraccionresiduon n_res,
extraccionresiduop p_res,
extraccionresiduok k_res,
contenidoresiduoc c_res,
extraccionresiduos s_res,
extraccionresiduoca ca_res,
extraccionresiduomg mg_res,
extraccionresiduob b_res
from agrae.cultivo c where idcultivo = {}